spring.application.name=order

server.port=8080

resilience4j.circuitbreaker.instances.payment.slidingWindowSize=5
resilience4j.circuitbreaker.instances.payment.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.payment.failureRateThreshold=50
resilience4j.circuitbreaker.instances.payment.waitDurationInOpenState=10s

# Enable circuit breaker health indicator
management.health.circuitbreakers.enabled=true
# Show full health details
management.endpoint.health.show-details=always
# Expose all actuator endpoints
management.endpoints.web.exposure.include=*